### ISSUE TITLE
net::ERR_INSECURE_RESPONSE error.

### ISSUE THREAD

**Issue by pyadav** [NekR/offline-plugin#77]
Everything working great if i navigate from root level but when i refresh a child path then its  try to make a request for **_/nested-route/sw.js_** which produce **DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html') Error.**

**Comment by NekR** [comment]
By default `offline-plugin` uses `relativePaths`. In your case, you have to turn them off, like this:
```js
new OfflinePlugin({
  relativePaths: false,
  publicPath: '/'
})
```

Hope it helps. Let me know if have any other problems with it. Thanks.

**Comment by pyadav** [comment]
Thanks @NekR It's work perfectly. I turn off relativePaths but forgot to mention relativePath :)

**Comment by NekR** [comment]
@pyadav yeah, it's a bit weird right, could be better :-)

**Comment by chaintan17** [comment]
I saw changelog that it's set to true by default in v3.0.0
I was wonderting does it has any benefits on this?
Because enable this realtivePaths, it create this bug and confuse newbie a little bit :)

**Comment by NekR** [comment]
`relativePaths` being `true` by default is fine because it's most universal setting. Without it, you always will have to set `publicPath`, but I want the plugin to work without any params, e.g. this `new OfflinePlugin()`.

However, there is a design mistake related to combination of `publicPath` and `relativePaths`. Obviously, setting `publicPath` should disable `relativePaths` (e.g. set it to `false`). But by some reason in was done in an other way and now you have to explicitly disable `relativePaths` when you use `publicPath`. Of course, this is a bug. But unfortunately I cannot fix it in `v3` because it's breaking change and I'm trying to follow semver here.

Bug with relation of `relativePaths` and `publicPath` is fixed in `v4`. `relativePaths` is still `true` by default and `publicPath` is `null`. Once `publicPath` is set to any string either in `OfflinePlugin` options or in `webpack.config.output.publicPath`, then `relativePaths` is automatically turned off (set to `false`). I hope this behavior is better one.

If you are interested, you can try `v4` by installing it with this command: 

```
npm install offline-plugin@next
```

Hope this helps :-)

**Comment by NekR** [comment]
That's relative path, set it to absolute.

**Comment by yelynn2015** [comment]
@NekR I have added the code you recommend, but it still not working. What should I do?

The error info:  
![image](https://user-images.githubusercontent.com/13792431/29067316-c16dab42-7c64-11e7-8b60-839f4d36231c.png)

**Comment by yelynn2015** [comment]
@NekR I have added the code you recommend, but it still not working. What should I do?

The error info:
![image](https://user-images.githubusercontent.com/13792431/29067346-dc0f1aa8-7c64-11e7-8de1-a46c1534eca5.png)

**Comment by gazpachu** [comment]
I'm also having the same problem with v4.8.3. My web app runs inside a folder http://website.tld/appName/...

![screen shot 2017-08-08 at 13 33 25](https://user-images.githubusercontent.com/1721288/29070177-67de896e-7c3e-11e7-8107-ef58abc19d3c.png)

This is my config:

```
new OfflinePlugin({
        relativePaths: false,
        publicPath: options.isProduction ? `/${appName}` : '/',
        caches: {
          main: [
            'app.*.css',
            'vendor.*.js',
            'app.*.js',
            'manifest.*.js'
          ],
          additional: [
            ':externals:'
          ],
          optional: [
            ':rest:'
          ]
        },
        externals: [
          options.isProduction ? `/${appName}` : '/'
        ],
        ServiceWorker: {
          navigateFallbackURL: options.isProduction ? `/${appName}` : '/'
        },
        AppCache: {
          FALLBACK: {
            '/': '/offline-page.html'
          }
        }
      })
```

**Comment by NekR** [comment]
Your service worker script should have JavaScript mime type and your appcache file should have its own manifest mime type. In your case they both have html's mime type. I van read that in console.

**Comment by gazpachu** [comment]
Sorry, I don't get it :-( In the setup, faqs or troubleshooting sections I don't see anything about mime types. Could you explain further what do I need to do? AFAIK, I don't have a service worker script. All I'm doing is loading the NPM package ???? Same thing for the appcache file.

**Comment by NekR** [comment]
Sorry, but I'm not going to teach web development here.

**Comment by gazpachu** [comment]
Right, the issue I'm having is that all the files ('sw.js` and the `appCache` folder) are being created in my output path (dist/), but I need them to be in (dist/appName). I've tried using `scope`, `outputPath` in the options but they are always being generated inside `dist/`.

**Comment by gazpachu** [comment]
This is what fixed it for me:

```
ServiceWorker: {
          output: `${appName}/sw.js`,
          navigateFallbackURL: `/${appName}`
        },
        AppCache: {
          directory: `${appName}/appcache`,
          FALLBACK: {
            '/': '/offline-page.html'
          }
        }
```

**Comment by yelynn2015** [comment]
I fix the issue when I set the public path in webpack.config.output rather than in OfflinePlugin, but don't know why.

**Comment by NekR** [comment]
@yelynn2015 you need it in webpack config, otherwise webpack itself won't work. offline-plugin options are just override, by default it takes what you specify in webpack config.

**Comment by yelynn2015** [comment]
Thank you! @NekR
